/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "e46.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x153_ASC_1(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Speed: start-bit 11, length 13, endianess intel, scaling 0.0625, offset 0 */
	x = ((uint16_t)(o->can_0x153_ASC_1.Speed)) & 0x1fff;
	x <<= 11; 
	i |= x;
	/* Unk4: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x153_ASC_1.Unk4)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Tyre_Pressure_Set: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x153_ASC_1.Tyre_Pressure_Set)) & 0x1;
	i |= x;
	/* Brake_Pedal_Pressed: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x153_ASC_1.Brake_Pedal_Pressed)) & 0x1;
	x <<= 4; 
	i |= x;
	*data = (i);
	o->can_0x153_ASC_1_tx = 1;
	return 8;
}

static int unpack_can_0x153_ASC_1(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Speed: start-bit 11, length 13, endianess intel, scaling 0.0625, offset 0 */
	x = (i >> 11) & 0x1fff;
	o->can_0x153_ASC_1.Speed = x;
	/* Unk4: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x153_ASC_1.Unk4 = x;
	/* Tyre_Pressure_Set: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x153_ASC_1.Tyre_Pressure_Set = x;
	/* Brake_Pedal_Pressed: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->can_0x153_ASC_1.Brake_Pedal_Pressed = x;
	o->can_0x153_ASC_1_rx = 1;
	o->can_0x153_ASC_1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x153_Speed(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x153_ASC_1.Speed);
	rval *= 0.0625;
	*out = rval;
	return 0;
}

int encode_can_0x153_Speed(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 16;
	o->can_0x153_ASC_1.Speed = in;
	return 0;
}

int decode_can_0x153_Unk4(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x153_ASC_1.Unk4);
	*out = rval;
	return 0;
}

int encode_can_0x153_Unk4(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x153_ASC_1.Unk4 = in;
	return 0;
}

int decode_can_0x153_Tyre_Pressure_Set(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x153_ASC_1.Tyre_Pressure_Set);
	*out = rval;
	return 0;
}

int encode_can_0x153_Tyre_Pressure_Set(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x153_ASC_1.Tyre_Pressure_Set = in;
	return 0;
}

int decode_can_0x153_Brake_Pedal_Pressed(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x153_ASC_1.Brake_Pedal_Pressed);
	*out = rval;
	return 0;
}

int encode_can_0x153_Brake_Pedal_Pressed(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x153_ASC_1.Brake_Pedal_Pressed = in;
	return 0;
}

int print_can_0x153_ASC_1(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Speed = (wire: %.0f)\n", (double)(o->can_0x153_ASC_1.Speed)));
	r = print_helper(r, fprintf(output, "Unk4 = (wire: %.0f)\n", (double)(o->can_0x153_ASC_1.Unk4)));
	r = print_helper(r, fprintf(output, "Tyre_Pressure_Set = (wire: %.0f)\n", (double)(o->can_0x153_ASC_1.Tyre_Pressure_Set)));
	r = print_helper(r, fprintf(output, "Brake_Pedal_Pressed = (wire: %.0f)\n", (double)(o->can_0x153_ASC_1.Brake_Pedal_Pressed)));
	return r;
}

static int pack_can_0x1f0_ABS_1(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Wheel_1_Left_Front_Speed: start-bit 0, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = ((uint16_t)(o->can_0x1f0_ABS_1.Wheel_1_Left_Front_Speed)) & 0xfff;
	i |= x;
	/* Wheel_2_Right_Front_Speed: start-bit 16, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = ((uint16_t)(o->can_0x1f0_ABS_1.Wheel_2_Right_Front_Speed)) & 0xfff;
	x <<= 16; 
	i |= x;
	/* Wheel_3_Left_Rear_Speed: start-bit 32, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = ((uint16_t)(o->can_0x1f0_ABS_1.Wheel_3_Left_Rear_Speed)) & 0xfff;
	x <<= 32; 
	i |= x;
	/* Wheel_4_Right_Rear_Speed: start-bit 48, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = ((uint16_t)(o->can_0x1f0_ABS_1.Wheel_4_Right_Rear_Speed)) & 0xfff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x1f0_ABS_1_tx = 1;
	return 8;
}

static int unpack_can_0x1f0_ABS_1(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Wheel_1_Left_Front_Speed: start-bit 0, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = i & 0xfff;
	o->can_0x1f0_ABS_1.Wheel_1_Left_Front_Speed = x;
	/* Wheel_2_Right_Front_Speed: start-bit 16, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = (i >> 16) & 0xfff;
	o->can_0x1f0_ABS_1.Wheel_2_Right_Front_Speed = x;
	/* Wheel_3_Left_Rear_Speed: start-bit 32, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = (i >> 32) & 0xfff;
	o->can_0x1f0_ABS_1.Wheel_3_Left_Rear_Speed = x;
	/* Wheel_4_Right_Rear_Speed: start-bit 48, length 12, endianess intel, scaling 0.0625, offset 0 */
	x = (i >> 48) & 0xfff;
	o->can_0x1f0_ABS_1.Wheel_4_Right_Rear_Speed = x;
	o->can_0x1f0_ABS_1_rx = 1;
	o->can_0x1f0_ABS_1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x1f0_Wheel_1_Left_Front_Speed(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f0_ABS_1.Wheel_1_Left_Front_Speed);
	rval *= 0.0625;
	*out = rval;
	return 0;
}

int encode_can_0x1f0_Wheel_1_Left_Front_Speed(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 16;
	o->can_0x1f0_ABS_1.Wheel_1_Left_Front_Speed = in;
	return 0;
}

int decode_can_0x1f0_Wheel_2_Right_Front_Speed(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f0_ABS_1.Wheel_2_Right_Front_Speed);
	rval *= 0.0625;
	*out = rval;
	return 0;
}

int encode_can_0x1f0_Wheel_2_Right_Front_Speed(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 16;
	o->can_0x1f0_ABS_1.Wheel_2_Right_Front_Speed = in;
	return 0;
}

int decode_can_0x1f0_Wheel_3_Left_Rear_Speed(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f0_ABS_1.Wheel_3_Left_Rear_Speed);
	rval *= 0.0625;
	*out = rval;
	return 0;
}

int encode_can_0x1f0_Wheel_3_Left_Rear_Speed(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 16;
	o->can_0x1f0_ABS_1.Wheel_3_Left_Rear_Speed = in;
	return 0;
}

int decode_can_0x1f0_Wheel_4_Right_Rear_Speed(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f0_ABS_1.Wheel_4_Right_Rear_Speed);
	rval *= 0.0625;
	*out = rval;
	return 0;
}

int encode_can_0x1f0_Wheel_4_Right_Rear_Speed(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 16;
	o->can_0x1f0_ABS_1.Wheel_4_Right_Rear_Speed = in;
	return 0;
}

int print_can_0x1f0_ABS_1(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Wheel_1_Left_Front_Speed = (wire: %.0f)\n", (double)(o->can_0x1f0_ABS_1.Wheel_1_Left_Front_Speed)));
	r = print_helper(r, fprintf(output, "Wheel_2_Right_Front_Speed = (wire: %.0f)\n", (double)(o->can_0x1f0_ABS_1.Wheel_2_Right_Front_Speed)));
	r = print_helper(r, fprintf(output, "Wheel_3_Left_Rear_Speed = (wire: %.0f)\n", (double)(o->can_0x1f0_ABS_1.Wheel_3_Left_Rear_Speed)));
	r = print_helper(r, fprintf(output, "Wheel_4_Right_Rear_Speed = (wire: %.0f)\n", (double)(o->can_0x1f0_ABS_1.Wheel_4_Right_Rear_Speed)));
	return r;
}

static int pack_can_0x1f3_x1F3(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* IDK1_unk4: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk4)) & 0xff;
	x <<= 24; 
	i |= x;
	/* IDK1_unk6: start-bit 38, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk6)) & 0x3;
	x <<= 38; 
	i |= x;
	/* IDK1_unk1: start-bit 7, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk1)) & 0x1;
	x <<= 7; 
	i |= x;
	/* IDK1_unk2: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk2)) & 0x1;
	x <<= 8; 
	i |= x;
	/* IDK1_unk3: start-bit 15, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk3)) & 0x1;
	x <<= 15; 
	i |= x;
	/* IDK1_unk5: start-bit 32, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk5)) & 0x1;
	x <<= 32; 
	i |= x;
	/* IDK1_unk7: start-bit 59, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f3_x1F3.IDK1_unk7)) & 0x1;
	x <<= 59; 
	i |= x;
	*data = (i);
	o->can_0x1f3_x1F3_tx = 1;
	return 8;
}

static int unpack_can_0x1f3_x1F3(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* IDK1_unk4: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x1f3_x1F3.IDK1_unk4 = x;
	/* IDK1_unk6: start-bit 38, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 38) & 0x3;
	o->can_0x1f3_x1F3.IDK1_unk6 = x;
	/* IDK1_unk1: start-bit 7, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 7) & 0x1;
	o->can_0x1f3_x1F3.IDK1_unk1 = x;
	/* IDK1_unk2: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->can_0x1f3_x1F3.IDK1_unk2 = x;
	/* IDK1_unk3: start-bit 15, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 15) & 0x1;
	o->can_0x1f3_x1F3.IDK1_unk3 = x;
	/* IDK1_unk5: start-bit 32, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0x1;
	o->can_0x1f3_x1F3.IDK1_unk5 = x;
	/* IDK1_unk7: start-bit 59, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 59) & 0x1;
	o->can_0x1f3_x1F3.IDK1_unk7 = x;
	o->can_0x1f3_x1F3_rx = 1;
	o->can_0x1f3_x1F3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x1f3_IDK1_unk4(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk4);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk4(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk4 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk6(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk6);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk6(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk6 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk1(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk1);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk1(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk1 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk2(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk2);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk2(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk2 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk3(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk3);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk3(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk3 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk5(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk5);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk5(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk5 = in;
	return 0;
}

int decode_can_0x1f3_IDK1_unk7(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f3_x1F3.IDK1_unk7);
	*out = rval;
	return 0;
}

int encode_can_0x1f3_IDK1_unk7(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f3_x1F3.IDK1_unk7 = in;
	return 0;
}

int print_can_0x1f3_x1F3(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "IDK1_unk4 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk4)));
	r = print_helper(r, fprintf(output, "IDK1_unk6 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk6)));
	r = print_helper(r, fprintf(output, "IDK1_unk1 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk1)));
	r = print_helper(r, fprintf(output, "IDK1_unk2 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk2)));
	r = print_helper(r, fprintf(output, "IDK1_unk3 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk3)));
	r = print_helper(r, fprintf(output, "IDK1_unk5 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk5)));
	r = print_helper(r, fprintf(output, "IDK1_unk7 = (wire: %.0f)\n", (double)(o->can_0x1f3_x1F3.IDK1_unk7)));
	return r;
}

static int pack_can_0x1f5_Steering_Angle_Sensor(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Steering_Angle: start-bit 0, length 15, endianess intel, scaling 0.045, offset 0 */
	x = ((uint16_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle)) & 0x7fff;
	i |= x;
	/* Steering_Angle_Velocity: start-bit 16, length 15, endianess intel, scaling 0.045, offset 0 */
	x = ((uint16_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity)) & 0x7fff;
	x <<= 16; 
	i |= x;
	/* Steering_Counter: start-bit 44, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Counter)) & 0xf;
	x <<= 44; 
	i |= x;
	/* Steering_Angle_Direction: start-bit 15, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Direction)) & 0x1;
	x <<= 15; 
	i |= x;
	/* Steering_Angle_Velocity_Direction: start-bit 31, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity_Direction)) & 0x1;
	x <<= 31; 
	i |= x;
	*data = (i);
	o->can_0x1f5_Steering_Angle_Sensor_tx = 1;
	return 8;
}

static int unpack_can_0x1f5_Steering_Angle_Sensor(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Steering_Angle: start-bit 0, length 15, endianess intel, scaling 0.045, offset 0 */
	x = i & 0x7fff;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle = x;
	/* Steering_Angle_Velocity: start-bit 16, length 15, endianess intel, scaling 0.045, offset 0 */
	x = (i >> 16) & 0x7fff;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity = x;
	/* Steering_Counter: start-bit 44, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 44) & 0xf;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Counter = x;
	/* Steering_Angle_Direction: start-bit 15, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 15) & 0x1;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Direction = x;
	/* Steering_Angle_Velocity_Direction: start-bit 31, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 31) & 0x1;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity_Direction = x;
	o->can_0x1f5_Steering_Angle_Sensor_rx = 1;
	o->can_0x1f5_Steering_Angle_Sensor_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x1f5_Steering_Angle(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle);
	rval *= 0.045;
	*out = rval;
	return 0;
}

int encode_can_0x1f5_Steering_Angle(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 22.2222;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle = in;
	return 0;
}

int decode_can_0x1f5_Steering_Angle_Velocity(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity);
	rval *= 0.045;
	*out = rval;
	return 0;
}

int encode_can_0x1f5_Steering_Angle_Velocity(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 22.2222;
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity = in;
	return 0;
}

int decode_can_0x1f5_Steering_Counter(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Counter);
	*out = rval;
	return 0;
}

int encode_can_0x1f5_Steering_Counter(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Counter = in;
	return 0;
}

int decode_can_0x1f5_Steering_Angle_Direction(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x1f5_Steering_Angle_Direction(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Direction = in;
	return 0;
}

int decode_can_0x1f5_Steering_Angle_Velocity_Direction(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x1f5_Steering_Angle_Velocity_Direction(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity_Direction = in;
	return 0;
}

int print_can_0x1f5_Steering_Angle_Sensor(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Steering_Angle = (wire: %.0f)\n", (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle)));
	r = print_helper(r, fprintf(output, "Steering_Angle_Velocity = (wire: %.0f)\n", (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity)));
	r = print_helper(r, fprintf(output, "Steering_Counter = (wire: %.0f)\n", (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Counter)));
	r = print_helper(r, fprintf(output, "Steering_Angle_Direction = (wire: %.0f)\n", (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Direction)));
	r = print_helper(r, fprintf(output, "Steering_Angle_Velocity_Direction = (wire: %.0f)\n", (double)(o->can_0x1f5_Steering_Angle_Sensor.Steering_Angle_Velocity_Direction)));
	return r;
}

static int pack_can_0x1f8_x1F8(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* x1F8Sig352: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x1f8_x1F8.x1F8Sig352)) & 0xffffffffffffffff;
	i |= x;
	*data = (i);
	o->can_0x1f8_x1F8_tx = 1;
	return 8;
}

static int unpack_can_0x1f8_x1F8(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* x1F8Sig352: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffffffffffff;
	o->can_0x1f8_x1F8.x1F8Sig352 = x;
	o->can_0x1f8_x1F8_rx = 1;
	o->can_0x1f8_x1F8_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x1f8_x1F8Sig352(const can_obj_e46_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x1f8_x1F8.x1F8Sig352);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint64_t)0;
		return -1;
	}
}

int encode_can_0x1f8_x1F8Sig352(can_obj_e46_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x1f8_x1F8.x1F8Sig352 = 0;
	if (in > 1)
		return -1;
	o->can_0x1f8_x1F8.x1F8Sig352 = in;
	return 0;
}

int print_can_0x1f8_x1F8(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "x1F8Sig352 = (wire: %.0f)\n", (double)(o->can_0x1f8_x1F8.x1F8Sig352)));
	return r;
}

static int pack_can_0x316_DME1(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* RPM: start-bit 16, length 16, endianess intel, scaling 0.156, offset 0 */
	x = ((uint16_t)(o->can_0x316_DME1.RPM)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* Torque_loss_of_consumers: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Torque_loss_of_consumers)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Torque_after_interventions: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Torque_after_interventions)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Torque_before_interventions: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Torque_before_interventions)) & 0xff;
	x <<= 32; 
	i |= x;
	/* Key: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Key)) & 0x1;
	i |= x;
	/* Ignition_on_DME_ready: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Ignition_on_DME_ready)) & 0x1;
	x <<= 2; 
	i |= x;
	/* Starter: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.Starter)) & 0x1;
	x <<= 4; 
	i |= x;
	/* AC_Clutch: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x316_DME1.AC_Clutch)) & 0x1;
	x <<= 6; 
	i |= x;
	*data = (i);
	o->can_0x316_DME1_tx = 1;
	return 8;
}

static int unpack_can_0x316_DME1(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* RPM: start-bit 16, length 16, endianess intel, scaling 0.156, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x316_DME1.RPM = x;
	/* Torque_loss_of_consumers: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x316_DME1.Torque_loss_of_consumers = x;
	/* Torque_after_interventions: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x316_DME1.Torque_after_interventions = x;
	/* Torque_before_interventions: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x316_DME1.Torque_before_interventions = x;
	/* Key: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->can_0x316_DME1.Key = x;
	/* Ignition_on_DME_ready: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 2) & 0x1;
	o->can_0x316_DME1.Ignition_on_DME_ready = x;
	/* Starter: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->can_0x316_DME1.Starter = x;
	/* AC_Clutch: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 6) & 0x1;
	o->can_0x316_DME1.AC_Clutch = x;
	o->can_0x316_DME1_rx = 1;
	o->can_0x316_DME1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x316_RPM(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x316_DME1.RPM);
	rval *= 0.156;
	*out = rval;
	return 0;
}

int encode_can_0x316_RPM(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 6.41026;
	o->can_0x316_DME1.RPM = in;
	return 0;
}

int decode_can_0x316_Torque_loss_of_consumers(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Torque_loss_of_consumers);
	*out = rval;
	return 0;
}

int encode_can_0x316_Torque_loss_of_consumers(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Torque_loss_of_consumers = in;
	return 0;
}

int decode_can_0x316_Torque_after_interventions(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Torque_after_interventions);
	*out = rval;
	return 0;
}

int encode_can_0x316_Torque_after_interventions(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Torque_after_interventions = in;
	return 0;
}

int decode_can_0x316_Torque_before_interventions(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Torque_before_interventions);
	*out = rval;
	return 0;
}

int encode_can_0x316_Torque_before_interventions(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Torque_before_interventions = in;
	return 0;
}

int decode_can_0x316_Key(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Key);
	*out = rval;
	return 0;
}

int encode_can_0x316_Key(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Key = in;
	return 0;
}

int decode_can_0x316_Ignition_on_DME_ready(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Ignition_on_DME_ready);
	*out = rval;
	return 0;
}

int encode_can_0x316_Ignition_on_DME_ready(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Ignition_on_DME_ready = in;
	return 0;
}

int decode_can_0x316_Starter(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.Starter);
	*out = rval;
	return 0;
}

int encode_can_0x316_Starter(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.Starter = in;
	return 0;
}

int decode_can_0x316_AC_Clutch(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x316_DME1.AC_Clutch);
	*out = rval;
	return 0;
}

int encode_can_0x316_AC_Clutch(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x316_DME1.AC_Clutch = in;
	return 0;
}

int print_can_0x316_DME1(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "RPM = (wire: %.0f)\n", (double)(o->can_0x316_DME1.RPM)));
	r = print_helper(r, fprintf(output, "Torque_loss_of_consumers = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Torque_loss_of_consumers)));
	r = print_helper(r, fprintf(output, "Torque_after_interventions = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Torque_after_interventions)));
	r = print_helper(r, fprintf(output, "Torque_before_interventions = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Torque_before_interventions)));
	r = print_helper(r, fprintf(output, "Key = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Key)));
	r = print_helper(r, fprintf(output, "Ignition_on_DME_ready = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Ignition_on_DME_ready)));
	r = print_helper(r, fprintf(output, "Starter = (wire: %.0f)\n", (double)(o->can_0x316_DME1.Starter)));
	r = print_helper(r, fprintf(output, "AC_Clutch = (wire: %.0f)\n", (double)(o->can_0x316_DME1.AC_Clutch)));
	return r;
}

static int pack_can_0x329_DME2(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Driver_Desired_Torque: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Driver_Desired_Torque)) & 0xff;
	x <<= 32; 
	i |= x;
	/* Throttle_Position: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Throttle_Position)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Engine_Temp: start-bit 8, length 8, endianess intel, scaling 0.75, offset -48.373 */
	x = ((uint8_t)(o->can_0x329_DME2.Engine_Temp)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Cycling_Number: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Cycling_Number)) & 0xff;
	i |= x;
	/* Atmospheric_Pressure: start-bit 16, length 8, endianess intel, scaling 2, offset 597 */
	x = ((uint8_t)(o->can_0x329_DME2.Atmospheric_Pressure)) & 0xff;
	x <<= 16; 
	i |= x;
	/* Brake_Light_Switch_Error: start-bit 49, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Brake_Light_Switch_Error)) & 0x1;
	x <<= 49; 
	i |= x;
	/* Clutch_Switch: start-bit 24, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Clutch_Switch)) & 0x1;
	x <<= 24; 
	i |= x;
	/* Engine_Running: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Engine_Running)) & 0x1;
	x <<= 28; 
	i |= x;
	/* Brake_Light_Switch: start-bit 48, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x329_DME2.Brake_Light_Switch)) & 0x1;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x329_DME2_tx = 1;
	return 8;
}

static int unpack_can_0x329_DME2(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Driver_Desired_Torque: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x329_DME2.Driver_Desired_Torque = x;
	/* Throttle_Position: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x329_DME2.Throttle_Position = x;
	/* Engine_Temp: start-bit 8, length 8, endianess intel, scaling 0.75, offset -48.373 */
	x = (i >> 8) & 0xff;
	o->can_0x329_DME2.Engine_Temp = x;
	/* Cycling_Number: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x329_DME2.Cycling_Number = x;
	/* Atmospheric_Pressure: start-bit 16, length 8, endianess intel, scaling 2, offset 597 */
	x = (i >> 16) & 0xff;
	o->can_0x329_DME2.Atmospheric_Pressure = x;
	/* Brake_Light_Switch_Error: start-bit 49, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 49) & 0x1;
	o->can_0x329_DME2.Brake_Light_Switch_Error = x;
	/* Clutch_Switch: start-bit 24, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0x1;
	o->can_0x329_DME2.Clutch_Switch = x;
	/* Engine_Running: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 28) & 0x1;
	o->can_0x329_DME2.Engine_Running = x;
	/* Brake_Light_Switch: start-bit 48, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0x1;
	o->can_0x329_DME2.Brake_Light_Switch = x;
	o->can_0x329_DME2_rx = 1;
	o->can_0x329_DME2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x329_Driver_Desired_Torque(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Driver_Desired_Torque);
	*out = rval;
	return 0;
}

int encode_can_0x329_Driver_Desired_Torque(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Driver_Desired_Torque = in;
	return 0;
}

int decode_can_0x329_Throttle_Position(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Throttle_Position);
	*out = rval;
	return 0;
}

int encode_can_0x329_Throttle_Position(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Throttle_Position = in;
	return 0;
}

int decode_can_0x329_Engine_Temp(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x329_DME2.Engine_Temp);
	rval *= 0.75;
	rval += -48.373;
	*out = rval;
	return 0;
}

int encode_can_0x329_Engine_Temp(can_obj_e46_h_t *o, double in) {
	assert(o);
	in += 48.373;
	in *= 1.33333;
	o->can_0x329_DME2.Engine_Temp = in;
	return 0;
}

int decode_can_0x329_Cycling_Number(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Cycling_Number);
	*out = rval;
	return 0;
}

int encode_can_0x329_Cycling_Number(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Cycling_Number = in;
	return 0;
}

int decode_can_0x329_Atmospheric_Pressure(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x329_DME2.Atmospheric_Pressure);
	rval *= 2;
	rval += 597;
	*out = rval;
	return 0;
}

int encode_can_0x329_Atmospheric_Pressure(can_obj_e46_h_t *o, double in) {
	assert(o);
	in += -597;
	in *= 0.5;
	o->can_0x329_DME2.Atmospheric_Pressure = in;
	return 0;
}

int decode_can_0x329_Brake_Light_Switch_Error(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Brake_Light_Switch_Error);
	*out = rval;
	return 0;
}

int encode_can_0x329_Brake_Light_Switch_Error(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Brake_Light_Switch_Error = in;
	return 0;
}

int decode_can_0x329_Clutch_Switch(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Clutch_Switch);
	*out = rval;
	return 0;
}

int encode_can_0x329_Clutch_Switch(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Clutch_Switch = in;
	return 0;
}

int decode_can_0x329_Engine_Running(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Engine_Running);
	*out = rval;
	return 0;
}

int encode_can_0x329_Engine_Running(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Engine_Running = in;
	return 0;
}

int decode_can_0x329_Brake_Light_Switch(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x329_DME2.Brake_Light_Switch);
	*out = rval;
	return 0;
}

int encode_can_0x329_Brake_Light_Switch(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x329_DME2.Brake_Light_Switch = in;
	return 0;
}

int print_can_0x329_DME2(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Driver_Desired_Torque = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Driver_Desired_Torque)));
	r = print_helper(r, fprintf(output, "Throttle_Position = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Throttle_Position)));
	r = print_helper(r, fprintf(output, "Engine_Temp = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Engine_Temp)));
	r = print_helper(r, fprintf(output, "Cycling_Number = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Cycling_Number)));
	r = print_helper(r, fprintf(output, "Atmospheric_Pressure = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Atmospheric_Pressure)));
	r = print_helper(r, fprintf(output, "Brake_Light_Switch_Error = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Brake_Light_Switch_Error)));
	r = print_helper(r, fprintf(output, "Clutch_Switch = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Clutch_Switch)));
	r = print_helper(r, fprintf(output, "Engine_Running = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Engine_Running)));
	r = print_helper(r, fprintf(output, "Brake_Light_Switch = (wire: %.0f)\n", (double)(o->can_0x329_DME2.Brake_Light_Switch)));
	return r;
}

static int pack_can_0x336_x336(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* x336Sig347: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x336_x336.x336Sig347)) & 0xffffffffffffffff;
	i |= x;
	*data = (i);
	o->can_0x336_x336_tx = 1;
	return 8;
}

static int unpack_can_0x336_x336(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* x336Sig347: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffffffffffff;
	o->can_0x336_x336.x336Sig347 = x;
	o->can_0x336_x336_rx = 1;
	o->can_0x336_x336_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x336_x336Sig347(const can_obj_e46_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x336_x336.x336Sig347);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint64_t)0;
		return -1;
	}
}

int encode_can_0x336_x336Sig347(can_obj_e46_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x336_x336.x336Sig347 = 0;
	if (in > 1)
		return -1;
	o->can_0x336_x336.x336Sig347 = in;
	return 0;
}

int print_can_0x336_x336(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "x336Sig347 = (wire: %.0f)\n", (double)(o->can_0x336_x336.x336Sig347)));
	return r;
}

static int pack_can_0x338_DME3(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Throttle_Position: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x338_DME3.Throttle_Position)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Clutch: start-bit 24, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x338_DME3.Clutch)) & 0x1;
	x <<= 24; 
	i |= x;
	/* Engine_Running: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x338_DME3.Engine_Running)) & 0x1;
	x <<= 28; 
	i |= x;
	/* Brake_Switch: start-bit 48, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x338_DME3.Brake_Switch)) & 0x1;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x338_DME3_tx = 1;
	return 8;
}

static int unpack_can_0x338_DME3(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Throttle_Position: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->can_0x338_DME3.Throttle_Position = x;
	/* Clutch: start-bit 24, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0x1;
	o->can_0x338_DME3.Clutch = x;
	/* Engine_Running: start-bit 28, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 28) & 0x1;
	o->can_0x338_DME3.Engine_Running = x;
	/* Brake_Switch: start-bit 48, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0x1;
	o->can_0x338_DME3.Brake_Switch = x;
	o->can_0x338_DME3_rx = 1;
	o->can_0x338_DME3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x338_Throttle_Position(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x338_DME3.Throttle_Position);
	*out = rval;
	return 0;
}

int encode_can_0x338_Throttle_Position(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x338_DME3.Throttle_Position = in;
	return 0;
}

int decode_can_0x338_Clutch(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x338_DME3.Clutch);
	*out = rval;
	return 0;
}

int encode_can_0x338_Clutch(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x338_DME3.Clutch = in;
	return 0;
}

int decode_can_0x338_Engine_Running(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x338_DME3.Engine_Running);
	*out = rval;
	return 0;
}

int encode_can_0x338_Engine_Running(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x338_DME3.Engine_Running = in;
	return 0;
}

int decode_can_0x338_Brake_Switch(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x338_DME3.Brake_Switch);
	*out = rval;
	return 0;
}

int encode_can_0x338_Brake_Switch(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x338_DME3.Brake_Switch = in;
	return 0;
}

int print_can_0x338_DME3(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Throttle_Position = (wire: %.0f)\n", (double)(o->can_0x338_DME3.Throttle_Position)));
	r = print_helper(r, fprintf(output, "Clutch = (wire: %.0f)\n", (double)(o->can_0x338_DME3.Clutch)));
	r = print_helper(r, fprintf(output, "Engine_Running = (wire: %.0f)\n", (double)(o->can_0x338_DME3.Engine_Running)));
	r = print_helper(r, fprintf(output, "Brake_Switch = (wire: %.0f)\n", (double)(o->can_0x338_DME3.Brake_Switch)));
	return r;
}

static int pack_can_0x501_x501(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* x501Sig34: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x501_x501.x501Sig34)) & 0xffffffffffffffff;
	i |= x;
	*data = (i);
	o->can_0x501_x501_tx = 1;
	return 8;
}

static int unpack_can_0x501_x501(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* x501Sig34: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffffffffffff;
	o->can_0x501_x501.x501Sig34 = x;
	o->can_0x501_x501_rx = 1;
	o->can_0x501_x501_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x501_x501Sig34(const can_obj_e46_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x501_x501.x501Sig34);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint64_t)0;
		return -1;
	}
}

int encode_can_0x501_x501Sig34(can_obj_e46_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x501_x501.x501Sig34 = 0;
	if (in > 1)
		return -1;
	o->can_0x501_x501.x501Sig34 = in;
	return 0;
}

int print_can_0x501_x501(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "x501Sig34 = (wire: %.0f)\n", (double)(o->can_0x501_x501.x501Sig34)));
	return r;
}

static int pack_can_0x545_DME4(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Fuel_Consumption: start-bit 8, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x545_DME4.Fuel_Consumption)) & 0xffff;
	x <<= 8; 
	i |= x;
	/* Charge_Light: start-bit 40, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x545_DME4.Charge_Light)) & 0x1;
	x <<= 40; 
	i |= x;
	/* Oil_Pressure_Light: start-bit 44, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x545_DME4.Oil_Pressure_Light)) & 0x1;
	x <<= 44; 
	i |= x;
	*data = (i);
	o->can_0x545_DME4_tx = 1;
	return 8;
}

static int unpack_can_0x545_DME4(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Fuel_Consumption: start-bit 8, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xffff;
	o->can_0x545_DME4.Fuel_Consumption = x;
	/* Charge_Light: start-bit 40, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0x1;
	o->can_0x545_DME4.Charge_Light = x;
	/* Oil_Pressure_Light: start-bit 44, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 44) & 0x1;
	o->can_0x545_DME4.Oil_Pressure_Light = x;
	o->can_0x545_DME4_rx = 1;
	o->can_0x545_DME4_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x545_Fuel_Consumption(const can_obj_e46_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x545_DME4.Fuel_Consumption);
	*out = rval;
	return 0;
}

int encode_can_0x545_Fuel_Consumption(can_obj_e46_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x545_DME4.Fuel_Consumption = in;
	return 0;
}

int decode_can_0x545_Charge_Light(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x545_DME4.Charge_Light);
	*out = rval;
	return 0;
}

int encode_can_0x545_Charge_Light(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x545_DME4.Charge_Light = in;
	return 0;
}

int decode_can_0x545_Oil_Pressure_Light(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x545_DME4.Oil_Pressure_Light);
	*out = rval;
	return 0;
}

int encode_can_0x545_Oil_Pressure_Light(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x545_DME4.Oil_Pressure_Light = in;
	return 0;
}

int print_can_0x545_DME4(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Fuel_Consumption = (wire: %.0f)\n", (double)(o->can_0x545_DME4.Fuel_Consumption)));
	r = print_helper(r, fprintf(output, "Charge_Light = (wire: %.0f)\n", (double)(o->can_0x545_DME4.Charge_Light)));
	r = print_helper(r, fprintf(output, "Oil_Pressure_Light = (wire: %.0f)\n", (double)(o->can_0x545_DME4.Oil_Pressure_Light)));
	return r;
}

static int pack_can_0x565_x565(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* IDK2_unk4: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk4)) & 0xff;
	x <<= 16; 
	i |= x;
	/* IDK2_unk7: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk7)) & 0xff;
	x <<= 56; 
	i |= x;
	/* IDK2_unk1: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk1)) & 0x1;
	x <<= 4; 
	i |= x;
	/* IDK2_unk2: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk2)) & 0x1;
	x <<= 6; 
	i |= x;
	/* IDK2_unk3: start-bit 13, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk3)) & 0x1;
	x <<= 13; 
	i |= x;
	/* IDK2_unk5: start-bit 25, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk5)) & 0x1;
	x <<= 25; 
	i |= x;
	/* IDK2_unk6: start-bit 41, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x565_x565.IDK2_unk6)) & 0x1;
	x <<= 41; 
	i |= x;
	*data = (i);
	o->can_0x565_x565_tx = 1;
	return 8;
}

static int unpack_can_0x565_x565(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* IDK2_unk4: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x565_x565.IDK2_unk4 = x;
	/* IDK2_unk7: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x565_x565.IDK2_unk7 = x;
	/* IDK2_unk1: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->can_0x565_x565.IDK2_unk1 = x;
	/* IDK2_unk2: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 6) & 0x1;
	o->can_0x565_x565.IDK2_unk2 = x;
	/* IDK2_unk3: start-bit 13, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 13) & 0x1;
	o->can_0x565_x565.IDK2_unk3 = x;
	/* IDK2_unk5: start-bit 25, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 25) & 0x1;
	o->can_0x565_x565.IDK2_unk5 = x;
	/* IDK2_unk6: start-bit 41, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 41) & 0x1;
	o->can_0x565_x565.IDK2_unk6 = x;
	o->can_0x565_x565_rx = 1;
	o->can_0x565_x565_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x565_IDK2_unk4(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk4);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x565_IDK2_unk4(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk4 = 0;
	if (in > 1)
		return -1;
	o->can_0x565_x565.IDK2_unk4 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk7(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk7);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x565_IDK2_unk7(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk7 = 0;
	if (in > 1)
		return -1;
	o->can_0x565_x565.IDK2_unk7 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk1(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk1);
	*out = rval;
	return 0;
}

int encode_can_0x565_IDK2_unk1(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk1 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk2(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk2);
	*out = rval;
	return 0;
}

int encode_can_0x565_IDK2_unk2(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk2 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk3(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk3);
	*out = rval;
	return 0;
}

int encode_can_0x565_IDK2_unk3(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk3 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk5(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk5);
	*out = rval;
	return 0;
}

int encode_can_0x565_IDK2_unk5(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk5 = in;
	return 0;
}

int decode_can_0x565_IDK2_unk6(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x565_x565.IDK2_unk6);
	*out = rval;
	return 0;
}

int encode_can_0x565_IDK2_unk6(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x565_x565.IDK2_unk6 = in;
	return 0;
}

int print_can_0x565_x565(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "IDK2_unk4 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk4)));
	r = print_helper(r, fprintf(output, "IDK2_unk7 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk7)));
	r = print_helper(r, fprintf(output, "IDK2_unk1 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk1)));
	r = print_helper(r, fprintf(output, "IDK2_unk2 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk2)));
	r = print_helper(r, fprintf(output, "IDK2_unk3 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk3)));
	r = print_helper(r, fprintf(output, "IDK2_unk5 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk5)));
	r = print_helper(r, fprintf(output, "IDK2_unk6 = (wire: %.0f)\n", (double)(o->can_0x565_x565.IDK2_unk6)));
	return r;
}

static int pack_can_0x610_x610(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* x610Sig39: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = ((uint64_t)(o->can_0x610_x610.x610Sig39)) & 0xffffffffffffffff;
	i |= x;
	*data = (i);
	o->can_0x610_x610_tx = 1;
	return 8;
}

static int unpack_can_0x610_x610(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* x610Sig39: start-bit 0, length 64, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffffffffffff;
	o->can_0x610_x610.x610Sig39 = x;
	o->can_0x610_x610_rx = 1;
	o->can_0x610_x610_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x610_x610Sig39(const can_obj_e46_h_t *o, uint64_t *out) {
	assert(o);
	assert(out);
	uint64_t rval = (uint64_t)(o->can_0x610_x610.x610Sig39);
	if (rval <= 1) {
		*out = rval;
		return 0;
	} else {
		*out = (uint64_t)0;
		return -1;
	}
}

int encode_can_0x610_x610Sig39(can_obj_e46_h_t *o, uint64_t in) {
	assert(o);
	o->can_0x610_x610.x610Sig39 = 0;
	if (in > 1)
		return -1;
	o->can_0x610_x610.x610Sig39 = in;
	return 0;
}

int print_can_0x610_x610(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "x610Sig39 = (wire: %.0f)\n", (double)(o->can_0x610_x610.x610Sig39)));
	return r;
}

static int pack_can_0x613_Instrument_Cluster(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Odometer: start-bit 0, length 16, endianess intel, scaling 10, offset 0 */
	x = ((uint16_t)(o->can_0x613_Instrument_Cluster.Odometer)) & 0xffff;
	i |= x;
	/* Running_Clock: start-bit 24, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x613_Instrument_Cluster.Running_Clock)) & 0xffff;
	x <<= 24; 
	i |= x;
	/* Fuel_Level: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x613_Instrument_Cluster.Fuel_Level)) & 0xff;
	x <<= 16; 
	i |= x;
	*data = (i);
	o->can_0x613_Instrument_Cluster_tx = 1;
	return 8;
}

static int unpack_can_0x613_Instrument_Cluster(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Odometer: start-bit 0, length 16, endianess intel, scaling 10, offset 0 */
	x = i & 0xffff;
	o->can_0x613_Instrument_Cluster.Odometer = x;
	/* Running_Clock: start-bit 24, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xffff;
	o->can_0x613_Instrument_Cluster.Running_Clock = x;
	/* Fuel_Level: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x613_Instrument_Cluster.Fuel_Level = x;
	o->can_0x613_Instrument_Cluster_rx = 1;
	o->can_0x613_Instrument_Cluster_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x613_Odometer(const can_obj_e46_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x613_Instrument_Cluster.Odometer);
	rval *= 10;
	*out = rval;
	return 0;
}

int encode_can_0x613_Odometer(can_obj_e46_h_t *o, double in) {
	assert(o);
	in *= 0.1;
	o->can_0x613_Instrument_Cluster.Odometer = in;
	return 0;
}

int decode_can_0x613_Running_Clock(const can_obj_e46_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x613_Instrument_Cluster.Running_Clock);
	*out = rval;
	return 0;
}

int encode_can_0x613_Running_Clock(can_obj_e46_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x613_Instrument_Cluster.Running_Clock = in;
	return 0;
}

int decode_can_0x613_Fuel_Level(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x613_Instrument_Cluster.Fuel_Level);
	*out = rval;
	return 0;
}

int encode_can_0x613_Fuel_Level(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x613_Instrument_Cluster.Fuel_Level = in;
	return 0;
}

int print_can_0x613_Instrument_Cluster(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Odometer = (wire: %.0f)\n", (double)(o->can_0x613_Instrument_Cluster.Odometer)));
	r = print_helper(r, fprintf(output, "Running_Clock = (wire: %.0f)\n", (double)(o->can_0x613_Instrument_Cluster.Running_Clock)));
	r = print_helper(r, fprintf(output, "Fuel_Level = (wire: %.0f)\n", (double)(o->can_0x613_Instrument_Cluster.Fuel_Level)));
	return r;
}

static int pack_can_0x615_x615(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* OutsideTemp: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x615_x615.OutsideTemp)) & 0xff;
	x <<= 24; 
	i |= x;
	*data = (i);
	o->can_0x615_x615_tx = 1;
	return 8;
}

static int unpack_can_0x615_x615(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* OutsideTemp: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x615_x615.OutsideTemp = x;
	o->can_0x615_x615_rx = 1;
	o->can_0x615_x615_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x615_OutsideTemp(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x615_x615.OutsideTemp);
	*out = rval;
	return 0;
}

int encode_can_0x615_OutsideTemp(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x615_x615.OutsideTemp = in;
	return 0;
}

int print_can_0x615_x615(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "OutsideTemp = (wire: %.0f)\n", (double)(o->can_0x615_x615.OutsideTemp)));
	return r;
}

static int pack_can_0x618_x618(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* IDK3unk1: start-bit 16, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x618_x618.IDK3unk1)) & 0x1;
	x <<= 16; 
	i |= x;
	/* IDK3unk2: start-bit 17, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x618_x618.IDK3unk2)) & 0x1;
	x <<= 17; 
	i |= x;
	/* IDK3unk3: start-bit 19, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x618_x618.IDK3unk3)) & 0x1;
	x <<= 19; 
	i |= x;
	/* IDK3unk4: start-bit 23, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x618_x618.IDK3unk4)) & 0x1;
	x <<= 23; 
	i |= x;
	*data = (i);
	o->can_0x618_x618_tx = 1;
	return 8;
}

static int unpack_can_0x618_x618(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* IDK3unk1: start-bit 16, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0x1;
	o->can_0x618_x618.IDK3unk1 = x;
	/* IDK3unk2: start-bit 17, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 17) & 0x1;
	o->can_0x618_x618.IDK3unk2 = x;
	/* IDK3unk3: start-bit 19, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 19) & 0x1;
	o->can_0x618_x618.IDK3unk3 = x;
	/* IDK3unk4: start-bit 23, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 23) & 0x1;
	o->can_0x618_x618.IDK3unk4 = x;
	o->can_0x618_x618_rx = 1;
	o->can_0x618_x618_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x618_IDK3unk1(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x618_x618.IDK3unk1);
	*out = rval;
	return 0;
}

int encode_can_0x618_IDK3unk1(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x618_x618.IDK3unk1 = in;
	return 0;
}

int decode_can_0x618_IDK3unk2(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x618_x618.IDK3unk2);
	*out = rval;
	return 0;
}

int encode_can_0x618_IDK3unk2(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x618_x618.IDK3unk2 = in;
	return 0;
}

int decode_can_0x618_IDK3unk3(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x618_x618.IDK3unk3);
	*out = rval;
	return 0;
}

int encode_can_0x618_IDK3unk3(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x618_x618.IDK3unk3 = in;
	return 0;
}

int decode_can_0x618_IDK3unk4(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x618_x618.IDK3unk4);
	*out = rval;
	return 0;
}

int encode_can_0x618_IDK3unk4(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x618_x618.IDK3unk4 = in;
	return 0;
}

int print_can_0x618_x618(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "IDK3unk1 = (wire: %.0f)\n", (double)(o->can_0x618_x618.IDK3unk1)));
	r = print_helper(r, fprintf(output, "IDK3unk2 = (wire: %.0f)\n", (double)(o->can_0x618_x618.IDK3unk2)));
	r = print_helper(r, fprintf(output, "IDK3unk3 = (wire: %.0f)\n", (double)(o->can_0x618_x618.IDK3unk3)));
	r = print_helper(r, fprintf(output, "IDK3unk4 = (wire: %.0f)\n", (double)(o->can_0x618_x618.IDK3unk4)));
	return r;
}

static int pack_can_0x61a_x61A(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	UNUSED(o);
	UNUSED(data);
	o->can_0x61a_x61A_tx = 1;
	return 8;
}

static int unpack_can_0x61a_x61A(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	UNUSED(o);
	UNUSED(data);
	if (dlc < 8)
		return -1;
	o->can_0x61a_x61A_rx = 1;
	o->can_0x61a_x61A_time_stamp_rx = time_stamp;
	return 8;
}

int print_can_0x61a_x61A(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	UNUSED(o);
	UNUSED(output);
	return 0;
}

static int pack_can_0x61f_x61F(can_obj_e46_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	register uint64_t i = 0;
	/* AutomaticLights: start-bit 0, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x61f_x61F.AutomaticLights)) & 0x1;
	x <<= 56; 
	m |= x;
	/* LeftTurnSignal: start-bit 22, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x61f_x61F.LeftTurnSignal)) & 0x1;
	x <<= 46; 
	m |= x;
	/* RightTurnSignal: start-bit 27, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x61f_x61F.RightTurnSignal)) & 0x1;
	x <<= 27; 
	i |= x;
	/* Headlights: start-bit 30, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x61f_x61F.Headlights)) & 0x1;
	x <<= 38; 
	m |= x;
	/* Lights: start-bit 36, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x61f_x61F.Lights)) & 0x1;
	x <<= 36; 
	i |= x;
	*data = reverse_byte_order(m)|(i);
	o->can_0x61f_x61F_tx = 1;
	return 8;
}

static int unpack_can_0x61f_x61F(can_obj_e46_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* AutomaticLights: start-bit 0, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 56) & 0x1;
	o->can_0x61f_x61F.AutomaticLights = x;
	/* LeftTurnSignal: start-bit 22, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 46) & 0x1;
	o->can_0x61f_x61F.LeftTurnSignal = x;
	/* RightTurnSignal: start-bit 27, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 27) & 0x1;
	o->can_0x61f_x61F.RightTurnSignal = x;
	/* Headlights: start-bit 30, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 38) & 0x1;
	o->can_0x61f_x61F.Headlights = x;
	/* Lights: start-bit 36, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 36) & 0x1;
	o->can_0x61f_x61F.Lights = x;
	o->can_0x61f_x61F_rx = 1;
	o->can_0x61f_x61F_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x61f_AutomaticLights(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x61f_x61F.AutomaticLights);
	*out = rval;
	return 0;
}

int encode_can_0x61f_AutomaticLights(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x61f_x61F.AutomaticLights = in;
	return 0;
}

int decode_can_0x61f_LeftTurnSignal(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x61f_x61F.LeftTurnSignal);
	*out = rval;
	return 0;
}

int encode_can_0x61f_LeftTurnSignal(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x61f_x61F.LeftTurnSignal = in;
	return 0;
}

int decode_can_0x61f_RightTurnSignal(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x61f_x61F.RightTurnSignal);
	*out = rval;
	return 0;
}

int encode_can_0x61f_RightTurnSignal(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x61f_x61F.RightTurnSignal = in;
	return 0;
}

int decode_can_0x61f_Headlights(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x61f_x61F.Headlights);
	*out = rval;
	return 0;
}

int encode_can_0x61f_Headlights(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x61f_x61F.Headlights = in;
	return 0;
}

int decode_can_0x61f_Lights(const can_obj_e46_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x61f_x61F.Lights);
	*out = rval;
	return 0;
}

int encode_can_0x61f_Lights(can_obj_e46_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x61f_x61F.Lights = in;
	return 0;
}

int print_can_0x61f_x61F(const can_obj_e46_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "AutomaticLights = (wire: %.0f)\n", (double)(o->can_0x61f_x61F.AutomaticLights)));
	r = print_helper(r, fprintf(output, "LeftTurnSignal = (wire: %.0f)\n", (double)(o->can_0x61f_x61F.LeftTurnSignal)));
	r = print_helper(r, fprintf(output, "RightTurnSignal = (wire: %.0f)\n", (double)(o->can_0x61f_x61F.RightTurnSignal)));
	r = print_helper(r, fprintf(output, "Headlights = (wire: %.0f)\n", (double)(o->can_0x61f_x61F.Headlights)));
	r = print_helper(r, fprintf(output, "Lights = (wire: %.0f)\n", (double)(o->can_0x61f_x61F.Lights)));
	return r;
}

int unpack_message(can_obj_e46_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x153: return unpack_can_0x153_ASC_1(o, data, dlc, time_stamp);
	case 0x1f0: return unpack_can_0x1f0_ABS_1(o, data, dlc, time_stamp);
	case 0x1f3: return unpack_can_0x1f3_x1F3(o, data, dlc, time_stamp);
	case 0x1f5: return unpack_can_0x1f5_Steering_Angle_Sensor(o, data, dlc, time_stamp);
	case 0x1f8: return unpack_can_0x1f8_x1F8(o, data, dlc, time_stamp);
	case 0x316: return unpack_can_0x316_DME1(o, data, dlc, time_stamp);
	case 0x329: return unpack_can_0x329_DME2(o, data, dlc, time_stamp);
	case 0x336: return unpack_can_0x336_x336(o, data, dlc, time_stamp);
	case 0x338: return unpack_can_0x338_DME3(o, data, dlc, time_stamp);
	case 0x501: return unpack_can_0x501_x501(o, data, dlc, time_stamp);
	case 0x545: return unpack_can_0x545_DME4(o, data, dlc, time_stamp);
	case 0x565: return unpack_can_0x565_x565(o, data, dlc, time_stamp);
	case 0x610: return unpack_can_0x610_x610(o, data, dlc, time_stamp);
	case 0x613: return unpack_can_0x613_Instrument_Cluster(o, data, dlc, time_stamp);
	case 0x615: return unpack_can_0x615_x615(o, data, dlc, time_stamp);
	case 0x618: return unpack_can_0x618_x618(o, data, dlc, time_stamp);
	case 0x61a: return unpack_can_0x61a_x61A(o, data, dlc, time_stamp);
	case 0x61f: return unpack_can_0x61f_x61F(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_e46_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x153: return pack_can_0x153_ASC_1(o, data);
	case 0x1f0: return pack_can_0x1f0_ABS_1(o, data);
	case 0x1f3: return pack_can_0x1f3_x1F3(o, data);
	case 0x1f5: return pack_can_0x1f5_Steering_Angle_Sensor(o, data);
	case 0x1f8: return pack_can_0x1f8_x1F8(o, data);
	case 0x316: return pack_can_0x316_DME1(o, data);
	case 0x329: return pack_can_0x329_DME2(o, data);
	case 0x336: return pack_can_0x336_x336(o, data);
	case 0x338: return pack_can_0x338_DME3(o, data);
	case 0x501: return pack_can_0x501_x501(o, data);
	case 0x545: return pack_can_0x545_DME4(o, data);
	case 0x565: return pack_can_0x565_x565(o, data);
	case 0x610: return pack_can_0x610_x610(o, data);
	case 0x613: return pack_can_0x613_Instrument_Cluster(o, data);
	case 0x615: return pack_can_0x615_x615(o, data);
	case 0x618: return pack_can_0x618_x618(o, data);
	case 0x61a: return pack_can_0x61a_x61A(o, data);
	case 0x61f: return pack_can_0x61f_x61F(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_e46_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x153: return print_can_0x153_ASC_1(o, output);
	case 0x1f0: return print_can_0x1f0_ABS_1(o, output);
	case 0x1f3: return print_can_0x1f3_x1F3(o, output);
	case 0x1f5: return print_can_0x1f5_Steering_Angle_Sensor(o, output);
	case 0x1f8: return print_can_0x1f8_x1F8(o, output);
	case 0x316: return print_can_0x316_DME1(o, output);
	case 0x329: return print_can_0x329_DME2(o, output);
	case 0x336: return print_can_0x336_x336(o, output);
	case 0x338: return print_can_0x338_DME3(o, output);
	case 0x501: return print_can_0x501_x501(o, output);
	case 0x545: return print_can_0x545_DME4(o, output);
	case 0x565: return print_can_0x565_x565(o, output);
	case 0x610: return print_can_0x610_x610(o, output);
	case 0x613: return print_can_0x613_Instrument_Cluster(o, output);
	case 0x615: return print_can_0x615_x615(o, output);
	case 0x618: return print_can_0x618_x618(o, output);
	case 0x61a: return print_can_0x61a_x61A(o, output);
	case 0x61f: return print_can_0x61f_x61F(o, output);
	default: break; 
	}
	return -1; 
}

